/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import constant.CommandDefine;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.smartcardio.CardException;
import javax.swing.JOptionPane;
import model.Employee;
import utils.ConnectCardUtils;
import utils.StringUtils;

/**
 *
 * @author datth
 */
public class ChangeFirstPin extends javax.swing.JFrame {

    /**
     * Creates new form ChangeFirstPin
     */
    public ChangeFirstPin() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setTitle("Change First Pin");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.getContentPane().setBackground(new Color(0, 153, 153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new ImagePanel("/images/2.jpg");
        jLabel1 = new javax.swing.JLabel();
        txt_old_pin = new javax.swing.JPasswordField();
        txt_new_pin = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_ụpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thay đổi mã Pin");

        txt_old_pin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_new_pin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã pin cũ :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã pin mới: ");

        btn_ụpdate.setBackground(new java.awt.Color(0, 153, 153));
        btn_ụpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_ụpdate.setForeground(new java.awt.Color(255, 255, 255));
        btn_ụpdate.setText("Cập nhật");
        btn_ụpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_ụpdate.setContentAreaFilled(false);
        btn_ụpdate.setFocusPainted(false);
        btn_ụpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ụpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_old_pin, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txt_new_pin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(btn_ụpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_old_pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_new_pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(51, 51, 51)
                .addComponent(btn_ụpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ụpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ụpdateActionPerformed
        // TODO add your handling code here:
        // validate password
        String oldPin = txt_old_pin.getText();
        String newPin = txt_new_pin.getText();
        if (newPin.equals(oldPin)) {
            JOptionPane.showMessageDialog(null, "Mã pin mới không được giống pin cũ");
            return;
        }
        boolean status = ConnectCardUtils.authenPin(oldPin);
        if (status) {
            byte[] result = null;
            result = ConnectCardUtils.sendApduHaveResponse(CommandDefine.GET_INFOR_CARD);
            String hexResult = StringUtils.bytesToHex(result); // Assuming you have this utility method
            System.out.println("Hex Result Length: " + hexResult.length());
            byte[] hexa = StringUtils.hexStringToByteArray(hexResult);
            System.out.println("Hexa : " + hexa);
            List<byte[]> parts = StringUtils.splitHexArrayBySemicolon(hexa);
            System.out.println("Parts : " + parts);
            // take infro
            String text_employee_code = StringUtils.hexArrayToText(parts.get(0));
            String text_name = StringUtils.hexArrayToText(parts.get(1));
            String text_birthday = StringUtils.hexArrayToText(parts.get(2));
            String text_position = StringUtils.hexArrayToText(parts.get(3));
            String text_pincode = txt_new_pin.getText();
            Employee new_employee = new Employee();
            new_employee.setEmployee_code(text_employee_code);
            new_employee.setName(text_name);
            new_employee.setBirthday(text_birthday);
            new_employee.setPosition(text_position);
            new_employee.setPin_code(text_pincode);
            String combinedString = String.join(";", text_employee_code, text_name, text_birthday, text_position, text_pincode);
            byte[] employeeData = combinedString.getBytes();
            byte[] prefix = new byte[]{0x00, 0x01, 0x00, 0x00};
            byte[] fullData = ConnectCardUtils.createDataWithPrefix(employeeData, prefix);
            String hexData = StringUtils.bytesToHex(fullData);
            System.out.println("Employee Data with Length : " + hexData.length());
            try {
                ConnectCardUtils.sendApduFromString(hexData, this);
                JOptionPane.showMessageDialog(null, "Đổi mã pin thành công");
                dispose();
            } catch (InterruptedException ex) {
                JOptionPane.showMessageDialog(null, "Đã có lỗi xảy ra");
                Logger.getLogger(ChangeFirstPin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btn_ụpdateActionPerformed
// public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EntranceBK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EntranceBK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EntranceBK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EntranceBK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChangeFirstPin().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ụpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_new_pin;
    private javax.swing.JPasswordField txt_old_pin;
    // End of variables declaration//GEN-END:variables
}
