/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import constant.CommandDefine;
import db.EmployeeDAO;
import java.awt.Color;
import utils.*;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Employee;

/**
 *
 * @author datth
 */
public class CreateNewCard extends javax.swing.JFrame {

    private EntranceBK entranceBk;
    private final int MAX_SIZE_IMAGE = 10240;
    private final String[] roles = {"Nhân Viên", "Giám đốc"};
    private String[] ids = {"NV", "GD"};
    private String currentCode = null;

    /**
     * Creates new form CreateNewCard
     */
    public CreateNewCard(EntranceBK entranceBk) {
        initComponents();
        setTitle("Create New Card");
        setVisible(true);
        setLocationRelativeTo(null);
        label_img.setText(null);
        btn_save_infor.setVisible(false);
        String employee_code = EmployeeUtils.generateEmployeeCode();
        currentCode = employee_code;
        txt_employee_code.setText("NV" + employee_code);
        txt_position.setVisible(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.entranceBk = entranceBk;

        comboBox_Role.removeAllItems();

        // Thêm từng mục vào comboBox_Role thủ công
        for (String role : roles) {
            comboBox_Role.addItem(role);
        }
        comboBox_Role.setSelectedItem("Nhân Viên");
        // Nếu bạn muốn chọn một giá trị mặc định, ví dụ chọn "Nhân Viên"
        comboBox_Role.setSelectedItem("Nhân Viên");
        this.getContentPane().setBackground(new Color(0, 153, 153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new ImagePanel("/images/3.jpg");
        btn_save_infor = new javax.swing.JButton();
        btn_choie_img = new javax.swing.JButton();
        btn_save_both_img = new javax.swing.JButton();
        txt_pincode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_position = new javax.swing.JTextField();
        title_position = new javax.swing.JLabel();
        txt_birthday = new javax.swing.JTextField();
        title_birthday = new javax.swing.JLabel();
        label_img = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        title_name = new javax.swing.JLabel();
        title_employee_code = new javax.swing.JLabel();
        txt_employee_code = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboBox_Role = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btn_save_infor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_save_infor.setText("Lưu");
        btn_save_infor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_inforActionPerformed(evt);
            }
        });

        btn_choie_img.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_choie_img.setText("Chọn ảnh");
        btn_choie_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choie_imgActionPerformed(evt);
            }
        });

        btn_save_both_img.setBackground(new java.awt.Color(255, 255, 153));
        btn_save_both_img.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_save_both_img.setForeground(new java.awt.Color(255, 255, 255));
        btn_save_both_img.setText("Lưu");
        btn_save_both_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_save_both_img.setContentAreaFilled(false);
        btn_save_both_img.setFocusPainted(false);
        btn_save_both_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_both_imgActionPerformed(evt);
            }
        });

        txt_pincode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_pincode.setText("123456");
        txt_pincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pincodeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã pin: ");

        txt_position.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        title_position.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_position.setForeground(new java.awt.Color(255, 255, 255));
        title_position.setText("Chức vụ :");

        txt_birthday.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_birthdayActionPerformed(evt);
            }
        });

        title_birthday.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_birthday.setForeground(new java.awt.Color(255, 255, 255));
        title_birthday.setText("Ngày sinh :");

        label_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        txt_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        title_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_name.setForeground(new java.awt.Color(255, 255, 255));
        title_name.setText("Họ và tên :");

        title_employee_code.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_employee_code.setForeground(new java.awt.Color(255, 255, 255));
        title_employee_code.setText("Mã nhân viên :");

        txt_employee_code.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_employee_code.setForeground(new java.awt.Color(255, 255, 255));
        txt_employee_code.setText("chưa có");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thông tin thẻ");

        comboBox_Role.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboBox_Role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_RoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(label_img, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btn_choie_img, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(title_position, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_pincode, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboBox_Role, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(title_birthday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(title_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(31, 31, 31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addComponent(txt_birthday))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(title_employee_code)
                        .addGap(18, 18, 18)
                        .addComponent(txt_employee_code, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(234, 234, 234))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_save_both_img, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_save_infor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_position, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save_infor))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_employee_code)
                            .addComponent(title_employee_code))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(title_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(title_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(title_position, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox_Role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_pincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_save_both_img))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(label_img, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_choie_img)))
                .addGap(0, 108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_birthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_birthdayActionPerformed

    private void txt_pincodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pincodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pincodeActionPerformed

    private void btn_save_both_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_both_imgActionPerformed
        // TODO add your handling code here:
        try {

            String text_employee_code = txt_employee_code.getText();
            String text_name = txt_name.getText();
            String text_birthday = txt_birthday.getText();
            String text_position = txt_position.getText();
            String text_pincode = txt_pincode.getText();
            if (StringUtils.isBlank(text_name) || StringUtils.isEmpty(text_name) || StringUtils.isNull(text_name)
                    || StringUtils.isBlank(text_birthday) || StringUtils.isEmpty(text_birthday)
                    || StringUtils.isNull(text_birthday)
                    //                    || StringUtils.isBlank(text_position)
                    //                    || StringUtils.isEmpty(text_position) || StringUtils.isNull(text_position)
                    || StringUtils.isBlank(text_pincode) || StringUtils.isEmpty(text_pincode)
                    || StringUtils.isNull(text_pincode)) {
                JOptionPane.showMessageDialog(null, "Có trường bị trống");
                return;
            }
            if (!isValidBirthday(text_birthday)) {
                JOptionPane.showMessageDialog(null, "Định dạng ngày không hợp lệ");
                return;
            }
            if(text_name.length() > 32){
                JOptionPane.showMessageDialog(null, "Tên quá dài");
                return;
            }
            String selectedRole = (String) comboBox_Role.getSelectedItem();

            // Tìm ID tương ứng với vai trò đã chọn
            String selectedId = null;
            for (int i = 0; i < roles.length; i++) {
                if (roles[i].equals(selectedRole)) {
                    selectedId = ids[i];  // Lấy giá trị ID tương ứng
                    break;
                }
            }

            Employee new_employee = new Employee();
            new_employee.setEmployee_code(text_employee_code);
            new_employee.setName(text_name);
            new_employee.setBirthday(text_birthday);
            new_employee.setPosition(selectedRole);
            new_employee.setPin_code(text_pincode);
            String combinedString = String.join(";", text_employee_code, text_name, text_birthday, selectedRole, text_pincode);
            byte[] employeeData = combinedString.getBytes();
            byte[] prefix = new byte[]{0x00, 0x01, 0x00, 0x00};
            byte[] fullData = ConnectCardUtils.createDataWithPrefix(employeeData, prefix);
            String hexData = StringUtils.bytesToHex(fullData);
            System.out.println("Employee Data with Length : " + hexData.length());
            ConnectCardUtils.sendApduFromString(hexData, this);
            Image avt = ImageSelectorComponent.selectedImage;
            if (avt != null) {
                byte[] imageBytes = ImageUtils.imageToBytes(avt, "png");
                ConnectCardUtils.sendExtendedApduFromString(imageBytes, this);
            }
            ConnectCardUtils.sendApdu(CommandDefine.CREATE_RSA_KEY);
            byte[] publicKey = ConnectCardUtils.sendApduHaveResponse(CommandDefine.GET_PUCKEY);
            String sPublicKey = StringUtils.bytesToHex(publicKey);
            System.out.println("Value of public Key : " + sPublicKey);
            EmployeeDAO.createAccount(text_employee_code, sPublicKey);
            //            ConnectCardUtils.disconnectCard();
            JOptionPane.showMessageDialog(null, "Tạo thẻ mới thành công");

            EnterCode enterCode = new EnterCode();
            entranceBk.dispose();
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Đã có lỗi xảy ra");
            Logger.getLogger(CreateNewCard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_save_both_imgActionPerformed

    private void btn_choie_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choie_imgActionPerformed
        // TODO add your handling code here:
        try {
//            ImageSelectorComponent imageSelector = new ImageSelectorComponent();
            ImageSelectorComponent.openImageSelector(this, label_img);
            Image img_select = ImageSelectorComponent.selectedImage;
            //        System.out.println("Image Selected : \n" + ImageUtils.imageToHex(img_select) );
            long sizeInBytes = ImageUtils.calculateImageSize(img_select);
            if (sizeInBytes < MAX_SIZE_IMAGE) {
                //                ImageUtils.printImageSize(img_select);
                byte[] imageBytes = ImageUtils.imageToBytes(img_select, "png");
                ImageUtils.displayImage(imageBytes, label_img);
            } else {
                JOptionPane.showMessageDialog(null, "Kích thước ảnh quá lớn vui lòng thử ảnh nhỏ hơn 10KB");
                ImageSelectorComponent.selectedImage = null;
            }
        } catch (Exception ex) {
            System.out.println("Exception :" + ex.getMessage());
        }

        // Gọi phương thức để mở hộp thoại chọn ảnh và cập nhật ảnh vào JLabel
    }//GEN-LAST:event_btn_choie_imgActionPerformed

    private void btn_save_inforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_inforActionPerformed
        // TODO add your handling code here:
        try {

            Employee new_employee = new Employee();
            String text_employee_code = txt_employee_code.getText();
            String text_name = txt_name.getText();
            String text_birthday = txt_birthday.getText();
            String text_position = txt_position.getText();
            new_employee.setEmployee_code(text_employee_code);
            new_employee.setName(text_name);
            new_employee.setBirthday(text_birthday);
            new_employee.setPosition(text_position);
            Image avt = ImageSelectorComponent.selectedImage;
            if (avt == null) {
                //            String employee_code, String name, String birthday, String position, Image avt
                new_employee.setAvt(null);
            } else {
                new_employee.setAvt(avt);
            }
            if (text_employee_code.length() != 8 || !isValidBirthday(text_birthday)) {
                JOptionPane.showMessageDialog(null, "Employee code must be exactly 8 characters. or Birthday match dd\\mm\\yyyy");
                return; // Stop further processing
            } else {
                byte[] employeeData = new_employee.toBytes(); // Chuyển thành byte
                //                System.out.println("Value of byte employee : "  + employeeData);
                byte[] prefix = new byte[]{0x00, 0x01, 0x00, 0x00}; // Thêm chuỗi 0x00, 0x00, 0x00, 0x00
                byte[] fullData = ConnectCardUtils.createDataWithPrefix(employeeData, prefix);
                // Chuyển mảng byte đầy đủ thành chuỗi hex để gửi
                String hexData = StringUtils.bytesToHex(fullData);
                System.out.println("Employee Data with Length : " + hexData.length());
                //            00 00 00 00 0C 613B613B613B613B61626364
                // Gọi hàm sendApdu để gửi lệnh APDU với dữ liệu mới
                ConnectCardUtils.sendApduFromString(hexData, this);
            }

            //            613B613B613B613B61626364
            //        "a;a;a;a;abcd"
            //            System.out.println("Employee : " + new_employee.bytesToHex(new_employee.toBytes()));
        } catch (Exception ex) {
            Logger.getLogger(CreateNewCard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_save_inforActionPerformed

    private void comboBox_RoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_RoleActionPerformed
        // TODO add your handling code here:
        String selectedRole = (String) comboBox_Role.getSelectedItem();

        // Tìm ID tương ứng với vai trò đã chọn
        String selectedId = null;
        for (int i = 0; i < roles.length; i++) {
            if (roles[i].equals(selectedRole)) {
                selectedId = ids[i];  // Lấy giá trị ID tương ứng
                break;
            }
        }
        txt_employee_code.setText(selectedId + currentCode);

        // In ra giá trị ID (ví dụ NV hoặc GD)
        System.out.println("Selected Role: " + selectedRole + " | Corresponding ID: " + selectedId);
    }//GEN-LAST:event_comboBox_RoleActionPerformed
    public boolean isValidBirthday(String birthday) {
        try {
            String regex = "^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/\\d{4}$"; // dd/mm/yyyy
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(birthday);
            return matcher.matches();
        } catch (Exception ex) {
            System.out.println("Exception :" + ex.getMessage());
            return false;
        }
    }

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CreateNewCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CreateNewCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CreateNewCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CreateNewCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            EntranceBK en = new EntranceBK();
//
//            public void run() {
//                new CreateNewCard(en).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_choie_img;
    private javax.swing.JButton btn_save_both_img;
    private javax.swing.JButton btn_save_infor;
    private javax.swing.JComboBox<String> comboBox_Role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_img;
    private javax.swing.JLabel title_birthday;
    private javax.swing.JLabel title_employee_code;
    private javax.swing.JLabel title_name;
    private javax.swing.JLabel title_position;
    private javax.swing.JTextField txt_birthday;
    private javax.swing.JLabel txt_employee_code;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_pincode;
    private javax.swing.JTextField txt_position;
    // End of variables declaration//GEN-END:variables
}
