/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import constant.CommandDefine;
import db.EmployeeDAO;
import utils.*;
import java.awt.Color;
import java.awt.Image;
import java.nio.charset.StandardCharsets;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.smartcardio.CardException;

/**
 *
 * @author proxc
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    int countAuthenCard = 0;
    private int addDay = 0;
    boolean status = false;
    static ConnectCardUtils connectCardUtils;

    public DashBoard() {
        initComponents();
        setTitle("BTL_SMART_CARD");
        setLocationRelativeTo(null);
        LocalDateTime now = LocalDateTime.now();
        // Format the date and time (optional)
        String formattedDateTime = now.format(formatter);
        txt_time.setText(formattedDateTime);
        connectCardUtils = new ConnectCardUtils();
        readInforCard();
    }

    public String getTime() {
        Date currentDate = new Date();

        // convert date to calendar
        Calendar c = Calendar.getInstance();
        c.setTime(currentDate);

        // manipulate date
        c.add(Calendar.DATE, addDay);

        // convert calendar to date
        Date currentDatePlusOne = c.getTime();

        String time = new SimpleDateFormat("HH:mm dd/MM/yyyy").format(currentDatePlusOne);
        return time;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        btnChangePin = new javax.swing.JButton();
        btnChangeInfo = new javax.swing.JButton();
        btnCheckin = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        btnCheckout1 = new javax.swing.JButton();
        btnThongke = new javax.swing.JButton();
        pnl_overlay = new javax.swing.JPanel();
        jPanel4 = new ImagePanel("/images/1.jpg");
        title_app = new javax.swing.JLabel();
        label_img = new javax.swing.JLabel();
        title_employee_code = new javax.swing.JLabel();
        title_name = new javax.swing.JLabel();
        title_birthday = new javax.swing.JLabel();
        title_position = new javax.swing.JLabel();
        txt_employee_code = new javax.swing.JLabel();
        txt_name = new javax.swing.JLabel();
        txt_birthday = new javax.swing.JLabel();
        txt_position = new javax.swing.JLabel();
        title_status = new javax.swing.JLabel();
        txt_status = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        btnChangeImage = new javax.swing.JButton();
        txt_dob = new javax.swing.JLabel();
        txt_time = new javax.swing.JLabel();
        btn_increase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(43, 51, 41));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(0, 153, 153));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        btnChangePin.setBackground(new java.awt.Color(57, 137, 186));
        btnChangePin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnChangePin.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePin.setText("Đổi mã PIN");
        btnChangePin.setBorder(null);
        btnChangePin.setContentAreaFilled(false);
        btnChangePin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnChangePin.setFocusPainted(false);
        btnChangePin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePinActionPerformed(evt);
            }
        });

        btnChangeInfo.setBackground(new java.awt.Color(57, 137, 186));
        btnChangeInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnChangeInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeInfo.setText("Đổi thông tin");
        btnChangeInfo.setBorder(null);
        btnChangeInfo.setContentAreaFilled(false);
        btnChangeInfo.setFocusPainted(false);
        btnChangeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeInfoActionPerformed(evt);
            }
        });

        btnCheckin.setBackground(new java.awt.Color(57, 137, 186));
        btnCheckin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCheckin.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckin.setText("Check in");
        btnCheckin.setBorder(null);
        btnCheckin.setContentAreaFilled(false);
        btnCheckin.setFocusPainted(false);
        btnCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckinActionPerformed(evt);
            }
        });

        btnCheckout.setBackground(new java.awt.Color(57, 137, 186));
        btnCheckout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("Check out");
        btnCheckout.setBorder(null);
        btnCheckout.setContentAreaFilled(false);
        btnCheckout.setFocusPainted(false);
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        btnCheckout1.setBackground(new java.awt.Color(57, 137, 186));
        btnCheckout1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCheckout1.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout1.setText("Đăng xuất");
        btnCheckout1.setBorder(null);
        btnCheckout1.setContentAreaFilled(false);
        btnCheckout1.setFocusPainted(false);
        btnCheckout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckout1ActionPerformed(evt);
            }
        });

        btnThongke.setBackground(new java.awt.Color(57, 137, 186));
        btnThongke.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThongke.setForeground(new java.awt.Color(255, 255, 255));
        btnThongke.setText("Thống kê");
        btnThongke.setBorder(null);
        btnThongke.setContentAreaFilled(false);
        btnThongke.setFocusPainted(false);
        btnThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThongke, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnChangePin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChangeInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckout1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnChangePin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnChangeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnThongke, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(btnCheckout1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 530));

        pnl_overlay.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_overlayMouseDragged(evt);
            }
        });
        pnl_overlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_overlayMousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(3276, 3276));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_app.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        title_app.setForeground(new java.awt.Color(255, 255, 204));
        title_app.setText("Thẻ ra vào công ty");
        title_app.setAlignmentX(0.5F);
        jPanel4.add(title_app, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 245, 73));

        label_img.setBackground(new java.awt.Color(255, 102, 102));
        label_img.setForeground(new java.awt.Color(255, 51, 153));
        label_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel4.add(label_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 118, 176));

        title_employee_code.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title_employee_code.setForeground(new java.awt.Color(255, 255, 255));
        title_employee_code.setText("Mã nhân viên :");
        jPanel4.add(title_employee_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        title_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title_name.setForeground(new java.awt.Color(255, 255, 255));
        title_name.setText("Họ tên : ");
        jPanel4.add(title_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 97, -1));

        title_birthday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title_birthday.setForeground(new java.awt.Color(255, 255, 255));
        title_birthday.setText("Ngày sinh : ");
        jPanel4.add(title_birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        title_position.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title_position.setForeground(new java.awt.Color(255, 255, 255));
        title_position.setText("Chức vụ :");
        jPanel4.add(title_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 78, -1));

        txt_employee_code.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_employee_code.setForeground(new java.awt.Color(255, 255, 255));
        txt_employee_code.setText("11111");
        jPanel4.add(txt_employee_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 240, 30));

        txt_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_name.setText("111111111111");
        jPanel4.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 240, 20));
        jPanel4.add(txt_birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 200, 471, -1));

        txt_position.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_position.setForeground(new java.awt.Color(255, 255, 255));
        txt_position.setText("11111111111111");
        jPanel4.add(txt_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 230, 20));

        title_status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title_status.setForeground(new java.awt.Color(255, 255, 255));
        title_status.setText("Trạng thái thẻ :");
        jPanel4.add(title_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        txt_status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_status.setForeground(new java.awt.Color(255, 255, 255));
        txt_status.setText("1111111111111");
        txt_status.setAlignmentX(0.5F);
        jPanel4.add(txt_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 240, 20));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 478, 37, -1));

        exit.setBackground(new java.awt.Color(231, 73, 134));
        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(231, 73, 134));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel4.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 26, 28));

        btnChangeImage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChangeImage.setText("Thay ảnh");
        btnChangeImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeImageActionPerformed(evt);
            }
        });
        jPanel4.add(btnChangeImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 110, 30));

        txt_dob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_dob.setForeground(new java.awt.Color(255, 255, 255));
        txt_dob.setText("1111111111111111");
        jPanel4.add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 230, 20));

        txt_time.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txt_time.setForeground(new java.awt.Color(0, 153, 204));
        txt_time.setText("null");
        txt_time.setAlignmentX(0.5F);
        jPanel4.add(txt_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 200, 30));

        btn_increase.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_increase.setText("Tăng Ngày");
        btn_increase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_increaseActionPerformed(evt);
            }
        });
        jPanel4.add(btn_increase, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        javax.swing.GroupLayout pnl_overlayLayout = new javax.swing.GroupLayout(pnl_overlay);
        pnl_overlay.setLayout(pnl_overlayLayout);
        pnl_overlayLayout.setHorizontalGroup(
            pnl_overlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 578, Short.MAX_VALUE)
        );
        pnl_overlayLayout.setVerticalGroup(
            pnl_overlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_overlayLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(pnl_overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 570, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    int xy;
    int xx;

    private void pnl_overlayMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_overlayMouseDragged
        // TODO add your handling code here:int x = evt.getXOnScreen();

    }//GEN-LAST:event_pnl_overlayMouseDragged

    private void pnl_overlayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_overlayMousePressed
        // TODO add your handling code here:


    }//GEN-LAST:event_pnl_overlayMousePressed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:

        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btnChangePinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePinActionPerformed
        // TODO add your handling code here:
        ChangeFirstPin updatePin = new ChangeFirstPin();
    }//GEN-LAST:event_btnChangePinActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void btnChangeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeInfoActionPerformed
        // TODO add your handling code here:
        ChangeInfor changeInfor = new ChangeInfor(this);
//        readInforCard();
//        changeInfor.dispose();
    }//GEN-LAST:event_btnChangeInfoActionPerformed

    private void btnCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckinActionPerformed
//        Authenzation auth = new Authenzation(status);
//        status
//        if(status){
        boolean allowCheckin = true;
        String id = getId();
        System.out.println("Value of Id : " + id);

        // Lấy dữ liệu checkin từ DB
        List dataCheckin = EmployeeDAO.queryDatabase(id);
        System.out.println("Nội dung của dataCheckin: " + dataCheckin);
        String checkinData = "";

        if (dataCheckin.size() > 2 && dataCheckin.get(2) != null) {
            checkinData = dataCheckin.get(2).toString();
        }

        // Kiểm tra xem nhân viên đã checkin trong ngày chưa
        if (!checkinData.isEmpty()) {
            String[] times = checkinData.split("-");
            String now = getTime();
            for (int i = 0; i < times.length; i++) {
                String date = times[i].split(" ")[1]; // lấy ngày tháng năm
                if (date.equals(now.split(" ")[1])) {
                    allowCheckin = false;
                    break;
                }
            }
        }

        if (allowCheckin) {
            String now = getTime();
            byte[] cmdSetCheckin = {(byte) 0x00, (byte) 0x20, (byte) 0x00, (byte) 0x00}; // Lệnh gửi check-in
            byte[] data = now.getBytes();

            // Gửi dữ liệu check-in lên applet
            System.out.println("Gửi check-in: " + now);
            connectCardUtils.sendAPDUtoApplet(cmdSetCheckin, data);

            // Kiểm tra phản hồi từ applet
            if (connectCardUtils.resAPDU.getSW1() == 0x90) {
                System.out.println("Check-in lưu thành công trong applet.");

                // Nhận dữ liệu check-in từ applet
                byte[] cmdGetCheckin = {(byte) 0x00, (byte) 0x22, (byte) 0x00, (byte) 0x00}; // Lệnh nhận check-in
                connectCardUtils.sendAPDUtoApplet(cmdGetCheckin, new byte[0]);

                if (connectCardUtils.resAPDU.getSW1() == 0x90) {
                    byte[] responseData = connectCardUtils.resAPDU.getData(); // Dữ liệu phản hồi
                    String timeFromApplet = new String(responseData).trim();
                    System.out.println("Dữ liệu từ applet: " + timeFromApplet);

                    // Ghi dữ liệu vào DB
                    String dataSend = !checkinData.isEmpty() ? checkinData + "-" + timeFromApplet : timeFromApplet;
                    int result = EmployeeDAO.setTimeCheck(true, id, dataSend);

                    if (result == 1) {
                        System.out.println("Lưu time checkin vào database thành công");
                        JOptionPane.showMessageDialog(this, "Checkin thành công.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Không thể lưu time checkin vào database.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Không nhận được dữ liệu từ applet.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Check-in không thành công trong applet.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn đã check-in rồi.");
        }
//        }else {
//            JOptionPane.showMessageDialog(this, "Xác thực không thành công nên không thể checkin");
//        }


    }//GEN-LAST:event_btnCheckinActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
//        try {
//            boolean statusAuth = sign_process();
//            if (statusAuth) {
        boolean allowCheckout = true;
        String id = getId();
        System.out.println("Value of Id : " + id);

        // Lấy dữ liệu từ database
        List data = EmployeeDAO.queryDatabase(id);
        String checkoutData = data.toArray()[3].toString();
        String checkinData = "";
        if (data.size() > 2 && data.get(2) != null) {
            checkinData = data.get(2).toString();
        }
        String now = getTime();
        boolean hasCheckedInToday = false;

        // Kiểm tra xem nhân viên đã checkin hôm nay chưa
        if (!checkinData.isEmpty()) {
            String[] times = checkinData.split("-");
            for (String time : times) {
                String date = time.split(" ")[1];
                if (date.equals(now.split(" ")[1])) {
                    hasCheckedInToday = true;
                    break;
                }
            }
        }

        if (!hasCheckedInToday) {
            JOptionPane.showMessageDialog(this, "Bạn cần checkin trước khi checkout.");
            return; // Thoát nếu chưa checkin
        }

        // Kiểm tra xem nhân viên đã checkout hôm nay chưa
        if (!checkoutData.isEmpty()) {
            String[] times = checkoutData.split("-");
            for (String time : times) {
                String date = time.split(" ")[1];
                if (date.equals(now.split(" ")[1])) {
                    allowCheckout = false;
                    break;
                }
            }
        }

        if (allowCheckout) {
            // Gửi lệnh checkout tới applet
            byte[] cmdSetCheckout = {(byte) 0x00, (byte) 0x21, (byte) 0x00, (byte) 0x00};
            byte[] data1 = now.getBytes();
            System.out.println("Gửi checkout: " + now);
            connectCardUtils.sendAPDUtoApplet(cmdSetCheckout, data1);

            // Kiểm tra phản hồi từ applet
            if (connectCardUtils.resAPDU.getSW1() == 0x90) {
                System.out.println("Checkout lưu thành công trong applet.");

                // Lấy dữ liệu checkout từ applet
                byte[] cmdGetCheckout = {(byte) 0x00, (byte) 0x23, (byte) 0x00, (byte) 0x00};
                connectCardUtils.sendAPDUtoApplet(cmdGetCheckout, new byte[0]);

                if (connectCardUtils.resAPDU.getSW1() == 0x90) {
                    byte[] responseData = connectCardUtils.resAPDU.getData(); // Dữ liệu phản hồi từ applet
                    String timeFromApplet = new String(responseData).trim();
                    System.out.println("Dữ liệu checkout từ applet: " + timeFromApplet);

                    // Ghi dữ liệu vào database
                    String dataSend = !checkoutData.isEmpty() ? checkoutData + "-" + timeFromApplet : timeFromApplet;
                    int result = EmployeeDAO.setTimeCheck(false, id, dataSend);

                    if (result == 1) {
                        System.out.println("Lưu time checkout vào database thành công");
                        JOptionPane.showMessageDialog(this, "Checkout thành công.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Không thể lưu time checkout vào database.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Không nhận được dữ liệu từ applet.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Checkout không thành công trong applet.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn đã checkout rồi.");

        }
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(DashBoard.class
//                    .getName()).log(Level.SEVERE, null, ex);
//        }


    }//GEN-LAST:event_btnCheckoutActionPerformed
    private boolean sign_process() throws Exception {
        boolean status = false;
        try {
            String id = getId();
            System.out.println("Value of Id : " + id);
            String publicKey = EmployeeDAO.getAccountById(id);
            System.out.println("Value of publicKey : " + publicKey);
            byte[] arrayPublicKey = StringUtils.hexStringToByteArray(publicKey);
            String random = StringUtils.getRandomString(10);
            System.out.println("Value of randomString : " + random);
            byte[] arrayRandom = random.getBytes();
            System.out.println("Array of random : " + arrayRandom);
            byte[] prefix = new byte[]{0x00, 0x18, 0x00, 0x00};
            byte[] fullData = ConnectCardUtils.createDataWithPrefix(arrayRandom, prefix);
            String hexData = StringUtils.bytesToHex(fullData);
            System.out.println("Employee Data with Length : " + hexData.length());
            byte[] dataSigned = ConnectCardUtils.sendApduFromStringHaveResponse(hexData);
            boolean authen = KeyUtils.verifySignature(arrayPublicKey, arrayRandom, dataSigned);
            if (authen) {
                status = true;
                System.out.println("ok");
                JOptionPane.showMessageDialog(null, "Xác thực thành công");
            } else {
                throw new Exception();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Xác thực không thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Xác thực không thành công");
        }
        return status;
    }
    private void btn_increaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_increaseActionPerformed
        // TODO add your handling code here:
        addDay++;
        String currentDateTimeText = txt_time.getText();
        LocalDateTime currentDateTime = LocalDateTime.parse(currentDateTimeText, formatter);

        // Tăng thêm 1 ngày
        LocalDateTime newDateTime = currentDateTime.plusDays(1);

        // Cập nhật lại JTextField
        txt_time.setText(newDateTime.format(formatter));
    }//GEN-LAST:event_btn_increaseActionPerformed
    public void readInforCard() {
        // infort
        try {
            byte[] result = ConnectCardUtils.sendApduHaveResponse(CommandDefine.GET_INFOR_CARD);
            String hexResult = StringUtils.bytesToHex(result); // Assuming you have this utility method
            System.out.println("Hex Result Length: " + hexResult.length());
            byte[] hexa = StringUtils.hexStringToByteArray(hexResult);
            System.out.println("Hexa : " + hexa);
            List<byte[]> parts = StringUtils.splitHexArrayBySemicolon(hexa);
            System.out.println("Parts : " + parts);
            txt_employee_code.setText(StringUtils.hexArrayToText(parts.get(0)));
            txt_name.setText(StringUtils.hexArrayToText(parts.get(1)));
            System.out.println("Value of Name after " + txt_name.getText());
            txt_dob.setText(StringUtils.hexArrayToText(parts.get(2)));
            txt_position.setText(StringUtils.hexArrayToText(parts.get(3)));
            String status;
            if (parts.get(4).length == 1 && parts.get(4)[0] == 0x00) {
                status = "active";
            } else {
//                btn_authen.setEnabled(false);
                status = "deactive";
            }
            txt_status.setText(status);
//            txt_pin.setText(StringUtils.hexArrayToText(parts.get(5)));
            // image
            byte[] image = ConnectCardUtils.sendApduHaveResponse(CommandDefine.GET_IMG);
            if (image.length > 0) {
                System.out.println("Do lon lon hon khonog");
                ImageUtils.displayImage(image, label_img);
            }

        } catch (Exception e) {
            System.out.println("Exception : " + e.getMessage());
        }

    }

    private String getId() {
        byte[] result = ConnectCardUtils.sendApduHaveResponse(CommandDefine.GET_ID);
        return StringUtils.hexArrayToText(result);
    }
    private void btnChangeImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeImageActionPerformed
        // TODO add your handling code here:
        try {
//            ImageSelectorComponent imageSelector = new ImageSelectorComponent();
            ImageSelectorComponent.openImageSelector(this, label_img);
            Image img_select = ImageSelectorComponent.selectedImage;
            Image avt = ImageSelectorComponent.selectedImage;
            if (avt != null) {
                new Thread(() -> {
                    try {
                        byte[] imageBytes = ImageUtils.imageToBytes(avt, "png");
//                        ConnectCardUtils.sendExtendedApduFromString(imageBytes,null);
                        ConnectCardUtils.sendExtendedApduFromStringForUpdateImage(imageBytes);
                        byte[] image = ConnectCardUtils.sendApduHaveResponse(CommandDefine.GET_IMG);
                        if (image.length > 0) {
                            System.out.println("Do lon lon hon khonog");
                            ImageUtils.displayImage(image, label_img);
                        }
//                        System.out.println("Code vẫn run tới đây mà");
//                        JOptionPane.showMessageDialog(null, "Thay ảnh thành công");
                    } catch (Exception e) {
                        System.out.println("Error in background thread: " + e.getMessage());
                        e.printStackTrace();
                    }
                }).start();
            }
//            
//            ImageUtils.printImageSize(img_select);

        } catch (Exception ex) {
            System.out.println("Exception :" + ex.getMessage());
        }
    }//GEN-LAST:event_btnChangeImageActionPerformed

    private void btnCheckout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckout1ActionPerformed
        // TODO add your handling code here:
        EntranceBK entranceBK = new EntranceBK();
        entranceBK.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCheckout1ActionPerformed

    private void btnThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeActionPerformed
        ThongKe thongke = new ThongKe();
    }//GEN-LAST:event_btnThongkeActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashBoard().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeImage;
    private javax.swing.JButton btnChangeInfo;
    private javax.swing.JButton btnChangePin;
    private javax.swing.JButton btnCheckin;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnCheckout1;
    private javax.swing.JButton btnThongke;
    private javax.swing.JButton btn_increase;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel label_img;
    private javax.swing.JPanel pnl_overlay;
    private javax.swing.JLabel title_app;
    private javax.swing.JLabel title_birthday;
    private javax.swing.JLabel title_employee_code;
    private javax.swing.JLabel title_name;
    private javax.swing.JLabel title_position;
    private javax.swing.JLabel title_status;
    private javax.swing.JLabel txt_birthday;
    private javax.swing.JLabel txt_dob;
    private javax.swing.JLabel txt_employee_code;
    private javax.swing.JLabel txt_name;
    private javax.swing.JLabel txt_position;
    private javax.swing.JLabel txt_status;
    private javax.swing.JLabel txt_time;
    // End of variables declaration//GEN-END:variables
}
