/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import constant.CommandDefine;
import db.EmployeeDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import utils.ConnectCardUtils;
import utils.KeyUtils;
import utils.StringUtils;

/**
 *
 * @author proxc
 */
public class EnterCode1 extends javax.swing.JFrame {

    int countAuthenCard = 0;
    private AuthCallback callback;

    /**
     * Creates new form NewJFrame
     */
    public EnterCode1(AuthCallback callback) {

        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Enter Pincode");
        setVisible(true);
        setLocationRelativeTo(null);
        txtPassword.setText("");
        String statusCardCurrent = getStatus();
        System.out.println("Take status of Card : " + statusCardCurrent);
        this.callback = callback;
        if (statusCardCurrent.equals("01")) {
            btnCheckPinCode.setEnabled(false);
            btnUnLockCard.setEnabled(true);
        } else {
            btnUnLockCard.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new ImagePanel("/images/3.jpg");
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCheckPinCode = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        btnUnLockCard = new javax.swing.JButton();
        exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Company Card");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nhập mã PIN");

        btnCheckPinCode.setBackground(new java.awt.Color(57, 137, 186));
        btnCheckPinCode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheckPinCode.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckPinCode.setText("Gửi");
        btnCheckPinCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnCheckPinCode.setContentAreaFilled(false);
        btnCheckPinCode.setFocusPainted(false);
        btnCheckPinCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckPinCodeActionPerformed(evt);
            }
        });

        btnUnLockCard.setBackground(new java.awt.Color(57, 137, 186));
        btnUnLockCard.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUnLockCard.setForeground(new java.awt.Color(255, 255, 255));
        btnUnLockCard.setText("Mở khóa");
        btnUnLockCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnUnLockCard.setContentAreaFilled(false);
        btnUnLockCard.setFocusPainted(false);
        btnUnLockCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnLockCardActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnCheckPinCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUnLockCard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))))
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(btnCheckPinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUnLockCard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int xy;
    int xx;

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
//        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:

        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btnCheckPinCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckPinCodeActionPerformed
        // TODO add your handling code here:
        String pin = txtPassword.getText();
        if (StringUtils.isBlank(pin) || StringUtils.isEmpty(pin) || StringUtils.isNull(pin)) {
            JOptionPane.showMessageDialog(
                    null,
                    "Vui lòng nhập mã pin.",
                    "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        boolean status = ConnectCardUtils.authenPin(pin);
        if (status) {

            countAuthenCard = 0;
            try {

                boolean statusAuthRsa = sign_process();
                if (statusAuthRsa) {
                    if (callback != null) {
                        callback.onAuthenticated(true);
                    }
                    dispose(); // Đóng form sau khi xác thực thành công
                } else {

                }

            } catch (Exception ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
//            readInforCard();

        } else {

            countAuthenCard++;
            // Kiểm tra số lần nhập sai và thông báo
            int remainingAttempts = 5 - countAuthenCard; // Tính số lần thử còn lại
            if (countAuthenCard >= 5) {
                JOptionPane.showMessageDialog(
                        null,
                        "Đã sai quá 5 lần, vui lòng mở khóa thẻ để tiếp tục.",
                        "Lỗi",
                        JOptionPane.ERROR_MESSAGE
                );
                btnCheckPinCode.setEnabled(false); // Vô hiệu hóa nút nhập mã PIN
                btnUnLockCard.setEnabled(true); // Hiển thị nút mở khóa thẻ
            } else {
                // Hiển thị thông báo số lần thử còn lại
                JOptionPane.showMessageDialog(
                        null,
                        "Mã PIN không đúng. Bạn còn " + remainingAttempts + " lần thử.",
                        "Cảnh báo",
                        JOptionPane.WARNING_MESSAGE
                );
            }

        }
    }//GEN-LAST:event_btnCheckPinCodeActionPerformed

    private void btnUnLockCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnLockCardActionPerformed
        // TODO add your handling code here:
        countAuthenCard = 0;
        ConnectCardUtils.sendApdu(CommandDefine.UNCLOCK_CARD);
        btnCheckPinCode.setEnabled(true);
        btnUnLockCard.setEnabled(false);
    }//GEN-LAST:event_btnUnLockCardActionPerformed
    private String getId() {
        byte[] result = ConnectCardUtils.sendApduHaveResponse(CommandDefine.GET_ID);
        return StringUtils.hexArrayToText(result);
    }

    private String getStatus() {
        byte[] result = ConnectCardUtils.getId(CommandDefine.GET_STATUS);
        return StringUtils.bytesToHex(result);
    }

    private boolean sign_process() throws Exception {
        boolean status = false;
        try {
            String id = getId();
            System.out.println("Value of Id : " + id);
            String publicKey = EmployeeDAO.getAccountById(id);
            System.out.println("Value of publicKey : " + publicKey);
            byte[] arrayPublicKey = StringUtils.hexStringToByteArray(publicKey);
            String random = StringUtils.getRandomString(10);
            System.out.println("Value of randomString : " + random);
            byte[] arrayRandom = random.getBytes();
            System.out.println("Array of random : " + arrayRandom);
            byte[] prefix = new byte[]{0x00, 0x18, 0x00, 0x00};
            byte[] fullData = ConnectCardUtils.createDataWithPrefix(arrayRandom, prefix);
            String hexData = StringUtils.bytesToHex(fullData);
            System.out.println("Employee Data with Length : " + hexData.length());
            byte[] dataSigned = ConnectCardUtils.sendApduFromStringHaveResponse(hexData);
            boolean authen = KeyUtils.verifySignature(arrayPublicKey, arrayRandom, dataSigned);
            if (authen) {
                status = true;
                System.out.println("authen ok");
//                JOptionPane.showMessageDialog(null, "Xác thực thành công");
            } else {
                throw new Exception();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Xác thực không thành công. Vui lòng ki?m tra l?i thông tin và th? l?i.",
                    "L?i",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Xác thực không thành công. Vui lòng ki?m tra l?i thông tin và th? l?i.",
                    "L?i",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        return status;
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EnterCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EnterCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EnterCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EnterCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EnterCode().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckPinCode;
    private javax.swing.JButton btnUnLockCard;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
