/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import constant.CommandDefine;
import utils.*;
import java.awt.Color;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.smartcardio.CardException;

/**
 *
 * @author datth
 */
public class Home extends javax.swing.JFrame {

    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    int countAuthenCard = 0;

    /**
     * Creates new form Home
     *
     */
    public Home() {
        initComponents();
        setTitle("BTL_SMART_CARD");
        setLocationRelativeTo(null);
        LocalDateTime now = LocalDateTime.now();
        // Format the date and time (optional)
        String formattedDateTime = now.format(formatter);
        txt_time.setText(formattedDateTime);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panel_top = new javax.swing.JPanel();
        panel_right = new javax.swing.JPanel();
        btn_create_card = new javax.swing.JButton();
        btn_read_infor = new javax.swing.JButton();
        btn_delete_card = new javax.swing.JButton();
        btn_connect_card = new javax.swing.JButton();
        btn_disconnect_card = new javax.swing.JButton();
        btn_change_pin_code = new javax.swing.JButton();
        btn_change_infor = new javax.swing.JButton();
        btn_checkin = new javax.swing.JButton();
        btn_checkout = new javax.swing.JButton();
        btn_statistic = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_test = new javax.swing.JButton();
        label_pin_code = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_pin_code = new javax.swing.JPasswordField();
        btn_authen = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        title_app = new javax.swing.JLabel();
        label_img = new javax.swing.JLabel();
        title_employee_code = new javax.swing.JLabel();
        title_name = new javax.swing.JLabel();
        title_birthday = new javax.swing.JLabel();
        title_position = new javax.swing.JLabel();
        txt_employee_code = new javax.swing.JLabel();
        txt_name = new javax.swing.JLabel();
        txt_birthday = new javax.swing.JLabel();
        txt_position = new javax.swing.JLabel();
        title_status = new javax.swing.JLabel();
        txt_status = new javax.swing.JLabel();
        btn_increase = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_time = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_top.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout panel_topLayout = new javax.swing.GroupLayout(panel_top);
        panel_top.setLayout(panel_topLayout);
        panel_topLayout.setHorizontalGroup(
            panel_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_topLayout.setVerticalGroup(
            panel_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        panel_right.setBackground(new java.awt.Color(153, 255, 255));

        btn_create_card.setText("Khởi tạo thẻ");
        btn_create_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_create_cardActionPerformed(evt);
            }
        });

        btn_read_infor.setText("Đọc từ thẻ");
        btn_read_infor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_read_inforActionPerformed(evt);
            }
        });

        btn_delete_card.setText("Xóa  thẻ");

        btn_connect_card.setText("Kết nối");
        btn_connect_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connect_cardActionPerformed(evt);
            }
        });

        btn_disconnect_card.setText("Ngắt kết nối");
        btn_disconnect_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_disconnect_cardActionPerformed(evt);
            }
        });

        btn_change_pin_code.setText("Thay đổi mã pin");
        btn_change_pin_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_change_pin_codeActionPerformed(evt);
            }
        });

        btn_change_infor.setText("Đổi thông tin");
        btn_change_infor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_change_inforActionPerformed(evt);
            }
        });

        btn_checkin.setText("Checkin");
        btn_checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkinActionPerformed(evt);
            }
        });

        btn_checkout.setText("Checkout");
        btn_checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkoutActionPerformed(evt);
            }
        });

        btn_statistic.setText("Thống kê");
        btn_statistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_statisticActionPerformed(evt);
            }
        });

        jButton1.setText("Mở khóa thẻ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_test.setText("Test function");
        btn_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_testActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_rightLayout = new javax.swing.GroupLayout(panel_right);
        panel_right.setLayout(panel_rightLayout);
        panel_rightLayout.setHorizontalGroup(
            panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rightLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_read_infor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_create_card, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete_card, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_connect_card, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_disconnect_card, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_change_pin_code, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_change_infor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_checkin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_checkout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_statistic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_test, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        panel_rightLayout.setVerticalGroup(
            panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rightLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btn_create_card)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_read_infor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_delete_card)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(15, 15, 15)
                .addComponent(btn_connect_card)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_disconnect_card)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_test)
                .addGap(57, 57, 57)
                .addComponent(btn_change_pin_code)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_change_infor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_checkin)
                .addGap(18, 18, 18)
                .addComponent(btn_checkout)
                .addGap(18, 18, 18)
                .addComponent(btn_statistic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label_pin_code.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setText("Mã pin :");

        btn_authen.setText("Xác thực");
        btn_authen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_authenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout label_pin_codeLayout = new javax.swing.GroupLayout(label_pin_code);
        label_pin_code.setLayout(label_pin_codeLayout);
        label_pin_codeLayout.setHorizontalGroup(
            label_pin_codeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(label_pin_codeLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pin_code, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_authen)
                .addGap(51, 51, 51))
        );
        label_pin_codeLayout.setVerticalGroup(
            label_pin_codeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(label_pin_codeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(label_pin_codeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_pin_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_authen))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        title_app.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        title_app.setForeground(new java.awt.Color(255, 51, 51));
        title_app.setText("Thẻ ra vào công ty");
        title_app.setAlignmentX(0.5F);

        label_img.setBackground(new java.awt.Color(255, 102, 102));
        label_img.setForeground(new java.awt.Color(255, 51, 153));
        label_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        title_employee_code.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        title_employee_code.setText("Mã nhân viên :");

        title_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        title_name.setText("Họ tên : ");

        title_birthday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        title_birthday.setText("Ngày sinh : ");

        title_position.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        title_position.setText("Chức vụ :");

        title_status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        title_status.setText("Trạng thái thẻ :");

        btn_increase.setText("Tăng Ngày");
        btn_increase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_increaseActionPerformed(evt);
            }
        });

        txt_time.setText("null");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(label_img, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title_employee_code, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title_birthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title_position, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_employee_code, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_birthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_position, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(title_app, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_increase)
                                .addGap(14, 14, 14)))
                        .addGap(20, 20, 20))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(label_img, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(title_app, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(title_employee_code)
                            .addComponent(txt_employee_code))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(title_name)
                            .addComponent(txt_name))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(title_birthday)
                            .addComponent(txt_birthday))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(title_position)
                            .addComponent(txt_position))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(title_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(17, 17, 17)
                .addComponent(btn_increase)
                .addGap(2, 2, 2)
                .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_pin_code, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_pin_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_create_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_create_cardActionPerformed
        // TODO add your handling code here:
        try {
            if (!ConnectCardUtils.isConnected()) {
                JOptionPane.showMessageDialog(null, "Vui lòng connect với card trước khi gửi lệnh");
                System.out.println("Vui long connect truoc khi gui lenh");
                return;
            }
            EntranceBK entranceBK = new EntranceBK();
            CreateNewCard creatNewCard = new CreateNewCard(entranceBK);
        } catch (Exception ex) {
            System.out.println("Exception :" + ex.getMessage());
        }
//      creatNewCard.setVisible(true);
    }//GEN-LAST:event_btn_create_cardActionPerformed

    private void btn_read_inforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_read_inforActionPerformed
        // TODO add your handling code here:
        try {
            readInforCard();
        } catch (Exception ex) {
            System.out.println("Exception :" + ex.getMessage());
        }


    }//GEN-LAST:event_btn_read_inforActionPerformed

    private void btn_disconnect_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_disconnect_cardActionPerformed
        // TODO add your handling code here:
        try {
            if (ConnectCardUtils.isConnected()) {
                ConnectCardUtils.disconnectCard();
                cleanData();
            } else {
                JOptionPane.showMessageDialog(null, "Bạn đã ngắt kết nối ");
            }
        } catch (Exception ex) {
            System.out.println("Exception :" + ex.getMessage());
        }

    }//GEN-LAST:event_btn_disconnect_cardActionPerformed

    private void btn_connect_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connect_cardActionPerformed
        // TODO add your handling code here:
        try {
            ConnectCardUtils.connectCard();
//            readInforCard();
        } catch (Exception ex) {
            System.out.println("Exception :" + ex.getMessage());
        }

    }//GEN-LAST:event_btn_connect_cardActionPerformed

    private void btn_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_testActionPerformed
        // TODO add your handling code here:
//        ConnectCardUtils.sendApdu(CommandDefine.TEST_CRYPTO);
        byte[] publicKey = null;
        publicKey = ConnectCardUtils.sendApduHaveResponse(CommandDefine.GET_PUCKEY);
        String sPublicKey = StringUtils.bytesToHex(publicKey);
        System.out.println("Value of public Key : " + sPublicKey);

    }//GEN-LAST:event_btn_testActionPerformed
//    public boolean authenPin(String pin) {
//        boolean statusAuthen = false;
//        try {
//
////            ConnectCardUtils.sendApdu(CommandDefine.GET_IMG);
////            String pin = txt_pin_code.getText();
//            byte[] pinBytes = pin.getBytes(StandardCharsets.UTF_8);
//            byte[] fullData = ConnectCardUtils.createDataWithPrefix(pinBytes, CommandDefine.CHECK_PIN.getValue());
//            String hexData = StringUtils.bytesToHex(fullData);
//            System.out.println("Employee Data with Length : " + hexData.length());
//            byte[] result = ConnectCardUtils.sendApduFromStringHaveResponse(hexData);
//            String checkPass = StringUtils.bytesToHex(result);
//            if (checkPass.equals("9000")) {
//                statusAuthen = true;
//                JOptionPane.showMessageDialog(null, "Mã pin hợp lệ");
//            } else {
//                JOptionPane.showMessageDialog(null, "Mã pin không hợp lệ");
//            }
//
//        } catch (Exception ex) {
//            System.out.println("Exception :" + ex.getMessage());
//        }
//        return statusAuthen;
//    }
    private void btn_change_pin_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_change_pin_codeActionPerformed
        // TODO add your handling code here:
        ChangeFirstPin updatePin = new ChangeFirstPin();
//        byte[] result = ConnectCardUtils.sendApduHaveResponse(CommandDefine.GET_INFOR_CARD);
//            String hexResult = StringUtils.bytesToHex(result); // Assuming you have this utility method
//            System.out.println("Hex Result Length: " + hexResult.length());

    }//GEN-LAST:event_btn_change_pin_codeActionPerformed

    private void btn_statisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_statisticActionPerformed
        // TODO add your handling code here:
//        ThongKe thongke = new ThongKe();
    }//GEN-LAST:event_btn_statisticActionPerformed

    private void btn_change_inforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_change_inforActionPerformed
        // TODO add your handling code here:
//        ChangeInfor changeInfor = new ChangeInfor();
    }//GEN-LAST:event_btn_change_inforActionPerformed

    private void btn_increaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_increaseActionPerformed
        // TODO add your handling code here:
        String currentDateTimeText = txt_time.getText();
        LocalDateTime currentDateTime = LocalDateTime.parse(currentDateTimeText, formatter);

        // Tăng thêm 1 ngày
        LocalDateTime newDateTime = currentDateTime.plusDays(1);

        // Cập nhật lại JTextField
        txt_time.setText(newDateTime.format(formatter));
    }//GEN-LAST:event_btn_increaseActionPerformed

    private void btn_authenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_authenActionPerformed
        // TODO add your handling code here:
        if (!ConnectCardUtils.isConnected()) {
            JOptionPane.showMessageDialog(null, "Vui lòng connect với card trước khi gửi lệnh");
            System.out.println("Vui long connect truoc khi gui lenh");
            return;
        }
        String pin = txt_pin_code.getText();
        if (pin == null) {
            JOptionPane.showMessageDialog(null, "Vui long nhap ma pin");
            return;
        }
        boolean status = ConnectCardUtils.authenPin(pin);
        if (status) {
            countAuthenCard = 0;
            readInforCard();
        } else {
            countAuthenCard++;
            if (countAuthenCard >= 3) {
                JOptionPane.showMessageDialog(null, "Đã sai quá 3 lần, vui lòng mở khóa thẻ để tiếp tục");
                btn_authen.setEnabled(false);
            }

        }

    }//GEN-LAST:event_btn_authenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConnectCardUtils.sendApdu(CommandDefine.UNCLOCK_CARD);
        btn_authen.setEnabled(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_checkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_checkinActionPerformed

    private void btn_checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_checkoutActionPerformed
    private void readInforCard() {
        // infort
        try {
            byte[] result = ConnectCardUtils.sendApduHaveResponse(CommandDefine.GET_INFOR_CARD);
            String hexResult = StringUtils.bytesToHex(result); // Assuming you have this utility method
            System.out.println("Hex Result Length: " + hexResult.length());
            byte[] hexa = StringUtils.hexStringToByteArray(hexResult);
            System.out.println("Hexa : " + hexa);
            List<byte[]> parts = StringUtils.splitHexArrayBySemicolon(hexa);
            System.out.println("Parts : " + parts);
            txt_employee_code.setText(StringUtils.hexArrayToText(parts.get(0)));
            txt_name.setText(StringUtils.hexArrayToText(parts.get(1)));
            txt_birthday.setText(StringUtils.hexArrayToText(parts.get(2)));
            txt_position.setText(StringUtils.hexArrayToText(parts.get(3)));
            String status;
            if (parts.get(4).length == 1 && parts.get(4)[0] == 0x00) {
                status = "active";
            } else {
                btn_authen.setEnabled(false);
                status = "deactive";
            }
            txt_status.setText(status);
//            txt_pin.setText(StringUtils.hexArrayToText(parts.get(5)));
            // image
            byte[] image = ConnectCardUtils.sendApduHaveResponse(CommandDefine.GET_IMG);
            if (image.length > 0) {
                System.out.println("Do lon lon hon khonog");
                ImageUtils.displayImage(image, label_img);
            }

        } catch (Exception e) {
            System.out.println("Exception : " + e.getMessage());
        }

    }

    private void cleanData() {
        txt_employee_code.setText("");
        txt_name.setText("");
        txt_birthday.setText("");
        txt_position.setText("");
        txt_position.setText("");
//        label_img.setText("");
        label_img.setIcon(null);
        txt_status.setText("");
    }
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_authen;
    private javax.swing.JButton btn_change_infor;
    private javax.swing.JButton btn_change_pin_code;
    private javax.swing.JButton btn_checkin;
    private javax.swing.JButton btn_checkout;
    private javax.swing.JButton btn_connect_card;
    private javax.swing.JButton btn_create_card;
    private javax.swing.JButton btn_delete_card;
    private javax.swing.JButton btn_disconnect_card;
    private javax.swing.JButton btn_increase;
    private javax.swing.JButton btn_read_infor;
    private javax.swing.JButton btn_statistic;
    private javax.swing.JButton btn_test;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label_img;
    private javax.swing.JPanel label_pin_code;
    private javax.swing.JPanel panel_right;
    private javax.swing.JPanel panel_top;
    private javax.swing.JLabel title_app;
    private javax.swing.JLabel title_birthday;
    private javax.swing.JLabel title_employee_code;
    private javax.swing.JLabel title_name;
    private javax.swing.JLabel title_position;
    private javax.swing.JLabel title_status;
    private javax.swing.JLabel txt_birthday;
    private javax.swing.JLabel txt_employee_code;
    private javax.swing.JLabel txt_name;
    private javax.swing.JPasswordField txt_pin_code;
    private javax.swing.JLabel txt_position;
    private javax.swing.JLabel txt_status;
    private javax.swing.JLabel txt_time;
    // End of variables declaration//GEN-END:variables
}
