/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import constant.CommandDefine;
import java.awt.Button;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.util.HashSet;
import java.util.Set;
import javax.swing.*;
import main.Main;

/**
 *
 * @author datth
 */
public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private Main smartCardMain;
    private boolean isConnect;
    public MainGui() {
        initComponents();
        // config for all app
        setTitle("Smart Card Connection");
        setSize(400, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        smartCardMain = new Main();
        isConnect = smartCardMain.isConnected();
        // config for text
        label_title.setText("Ví dụ connect JavaCard");
        label_title.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 28));
        label_title.setHorizontalAlignment(SwingConstants.CENTER);
        label_title.setForeground(Color.red);
        // config for btn
        send_apdu.setText("Send APDU");
        send_apdu.setFocusPainted(false);
        btn_connect.setFocusPainted(false); // Tắt hiệu ứng focus
        btn_connect.setPreferredSize(new Dimension(150, 50));
        if (isConnect) {
            status_connect.setText("connected");
            setBtnDisconnect(btn_connect);
        } else {
            status_connect.setText("notconnected");
            setBtnConnect(btn_connect);
        }
        // config select option
        cbox_command.addItem("SEND_APDU");
        cbox_command.addItem("OTHER_SEND_APDU");
        cbox_command.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_connect = new javax.swing.JButton();
        label_title = new javax.swing.JLabel();
        status_connect = new javax.swing.JLabel();
        send_apdu = new javax.swing.JButton();
        cbox_command = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_connect.setText("jButton1");
        btn_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectActionPerformed(evt);
            }
        });

        label_title.setText("Title");
        label_title.setAlignmentX(0.5F);

        status_connect.setText("status_connect");

        send_apdu.setText("jButton1");
        send_apdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_apduActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btn_connect))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_title)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(status_connect)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(cbox_command, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(send_apdu)))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(label_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(status_connect)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(send_apdu)
                            .addComponent(cbox_command, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)))
                .addComponent(btn_connect)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connectActionPerformed
        // TODO add your handling code here:
        isConnect = smartCardMain.isConnected();
        System.out.println("Value of isConnect : " + isConnect);
        if(isConnect){
           if(smartCardMain.disconnectCard()){
               setBtnConnect(btn_connect);
           }
        }else {
            if(smartCardMain.connectCard()){
                setBtnDisconnect(btn_connect);
            }else {
                System.out.println("Chua connect duoc");
            }
            
        }
    }//GEN-LAST:event_btn_connectActionPerformed

    private void send_apduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_apduActionPerformed
        // TODO add your handling code here:
        String selectedCommand = (String) cbox_command.getSelectedItem();
        CommandDefine command = CommandDefine.valueOf(selectedCommand);
        smartCardMain.sendApdu(command);
    }//GEN-LAST:event_send_apduActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
////                new GUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_connect;
    private javax.swing.JComboBox<String> cbox_command;
    private javax.swing.JLabel label_title;
    private javax.swing.JButton send_apdu;
    private javax.swing.JLabel status_connect;
    // End of variables declaration//GEN-END:variables
    public void setBtnConnect(JButton btn_connect) {
//        smartCardMain.setConnected(true);
        btn_connect.setForeground(Color.WHITE);
        btn_connect.setBackground(new Color(30, 144, 255));
        btn_connect.setText("Connect!");
        status_connect.setText("Not connected");
        // Kích thước nút
    }

    public void setBtnDisconnect(JButton btn_connect) {
//        smartCardMain.setConnected(false);
        btn_connect.setForeground(Color.WHITE);  // Màu chữ trắng
        btn_connect.setBackground(new Color(255, 140, 0));  // Màu nền orange (cam)
        btn_connect.setText("Disconnect!");
        status_connect.setText("Connected");
    }
}
